### ISSUE TITLE
iOS秒开H5实战总结 | RAMBO

### ISSUE THREAD

**Issue by RamboQiu** [RamboQiu/RamboQiu.github.io#26]
https://ramboqiu.github.io/posts/iOS%E7%A7%92%E5%BC%80H5%E5%AE%9E%E6%88%98%E6%80%BB%E7%BB%93/ 

 iOS平台的H5网页加载步骤：

**Comment by 451222664** [comment]
【wk拦截同firbase performance的hook冲突会导致崩溃】
你好，这个问题你是怎么解决的呢
